### ISSUE TITLE
Feedback on Action Update scheme

### ISSUE THREAD

**Issue by prenagha** [prenagha/launchbar#1]
Would like to get feedback from Objective Development and experienced LaunchBar custom action developers on a general approach for action updating.

Custom actions are great, but painful to keep up to date. Rather than all of us individually build updating mechanisms, and clutter our actions with update related UI and pinging, I thought it would be useful to have a general approach that we could all use.

To that end I have built a prototype action that checks each custom action a user has installed and figures out if a newer version exists. It reports on results and provides options for user
- visit `LBWebsite`
- see `LBChangelog`
- download `LBDownload` (trigger browser open URL)

The trick is for all custom actions to include the `/LBDescription/LBUpdate` key in their `Info.plist` as a string URL reference to a remote server of the `Info.plist` of most recent version

_Optional_ keys to enable changelog and download link features:
- `/LBDescription/LBChangelog` - string changelog text to display to user
- `/LBDescription/LBDownload` - string URL reference to remote server where most recent action package can be downloaded

For more info:
- [Action Update Action General Info](http://prenagha.github.io/launchbar/updates.html)
- [Action Update Action Developer Info](https://github.com/prenagha/launchbar/blob/master/Updates.lbaction/Contents/Scripts/README.md)
- [Action Update Action Download](https://dl.dropboxusercontent.com/u/1094926/lbdist/Updates.lbaction)

Would be great if folks would review the above and see if we can all agree on the `Info.plist` keys to use. Once we agree on that, we all update our actions accordingly and anyone can implement an action version checker themselves, or use mine. Hopefully one day LaunchBar will have native support for this and can leverage the keys we have all standardized on.

ping: @nbjahan @mlinzner @facetheheat @Ptujec @zettt @gillibrand @aristidesfl @ttscoff @itspriddle @Duhemm @kkiani @jasonrudolph @hlissner @nosrac @marcomasser @heikowitte

**Comment by hlissner** [comment]
This looks good. I'll gladly incorporate it into my actions. Though, see #2 for my concerns with LBDownload.

**Comment by prenagha** [comment]
To clarify `LBDownload` is an optional key. If present I will try to download if, if absent that is the action telling me not to try and download. See comments to #2

**Comment by prenagha** [comment]
Interested in group's thoughts on anonymous action usage reporting, see issue #4

**Comment by ghost** [comment]
Thanks, definitely with you on this, singular approach to updating is important.

**Auto Updating**: we could use http://semver.org/ to decide auto update patch/minor releases  and not auto update major releases.
**Changelog**: I think additional _optional_ key is required for the change log info (I used **LBChangelog**)
**Revert bad updates**: we need to archive the old version before replacing it with the new version

with these in mind we can safely update an action with single action without the need to download then install approach.

**Comment by prenagha** [comment]
Auto download seems more problematic than worth it. So in v1.5 fc2905c0d64f30c9f8190f3e05e0f0ca7f6e6d73 I have changed the action to present user with a set of LB items to decide what to do with an action with a newer version (visit website, see changelog, download...)
Download just opens the download URL in the browser, normally causing download - no different than if user did it themselves normally.
I also added support for `LBChangelog` key

**Comment by mlinzner** [comment]
Thanks Padraic for your efforts, I appreciate it. 

Speaking as a LB Action developer and user: I see your point and it would be great to make updates easier. I'm happy to include that into my actions. I'm not happy about the usage reporting (#4) though, I do not see a reason why we need that.

Speaking for Objective Development: We have plans to add automatic update checks for actions in the future. Right now we are happy to support your proposed solution wherever we can. I also believe that our plans can build upon the keys you introduce now. But @marcomasser (one of the developers responsible for the LaunchBar action support) is probably the best to comment on this.

**Comment by marcomasser** [comment]
I agree to what @mlinzner wrote: We want to implement a mechanism for (automatic) updates of installed actions in a future release, we discussed it internally a couple of times already, but we’re not working on it yet.

Disclaimer: The names of the keys you defined look fine to me but because we haven’t sketched this feature out, I can’t promise that we will name them exactly that.

Also, the stuff you do is awesome!

**Comment by prenagha** [comment]
@mlinzner @marcomasser thanks for the feedback. was actually hoping that we could get the keys agreed to now and you all put them in the official LaunchBar documentation and state "for future use" or something. Once actions get published it is impossible to take them back, and so the longer we wait to get the right keys into them, the more users we have with actions that are effectively not-updatable.

**Comment by marcomasser** [comment]
@prenagha We discussed this some more and reached the following conclusions:
1. In the `LBDescription` dictionary, there’s a `LBWebsite` key which we will rename to `LBWebsiteURL` in the next LaunchBar release (due before OS X El Capitan will be released on 2015-09-30). For forward-compatibility, this version will prefer `LBWebsiteURL` but will fall back to `LBWebsite` if the newer key isn’t there. The bundled Action Editor will still retain the old behavior and we will switch that to the new key in a later release.
2. The keys related to automatic updating of LaunchBar Actions inside the `LBDescription` dictionary will be named: `LBUpdateURL`, `LBDownloadURL` and `LBChangelog` (no “URL” suffix because it’s not an URL, just a plain string).

We would propose that you append the “URL” suffix to `LBUpdate` and `LBDownload`. Also, if you’d check for `LBWebsiteURL` and fall back to `LBWebsite`, your action’s behavior would match LaunchBar’s.

Regarding the documentation: We’d be happy to include these new keys as you suggest. If you want, we could also include a link to your action. Would it be OK for you if we’d link to the [README](https://github.com/prenagha/launchbar/blob/master/Updates.lbaction/Contents/Scripts/README.md) of your Updates action?

**Comment by prenagha** [comment]
@marcomasser I have released v2.0 with support for `LBWebsiteURL` (with fallback), `LBUpdateURL`, and `LBChangelog`
I say we all agree to that and lets move forward.

A link would be great, and the [Action Info Page](https://prenagha.github.io/launchbar/updates.html) is probably better to link to.

Thanks everyone for working together to figure this out. Now lets get going updating our actions with the new keys!

**Comment by marcomasser** [comment]
Done. The new keys (`LBChangelog`, `LBDownloadURL` and `LBUpdateURL`) and the changed key (`LBWebsiteURL`) are documented on the [Action Info.plist](https://developer.obdev.at/resources/documentation/launchbar-developer-documentation/#/action-info-plist) page and a new paragraph called [Updating Actions](https://developer.obdev.at/resources/documentation/launchbar-developer-documentation/#/distributing-actions/updating-actions) in the [Distributing Actions](https://developer.obdev.at/resources/documentation/launchbar-developer-documentation/#/distributing-actions) section points to your action.

Thanks for your awesome work and your input!

**Comment by prenagha** [comment]
@marcomasser 
Awesome. Thanks.
My only comment would be in LBUpdateURL to state that it must be the Info.plist of the most recent version, I certainly expect that for my action and suspect you will want same when LB implements action updating.

**Comment by marcomasser** [comment]
Agreed. I changed the wording to make that clearer.

**Comment by youtextme** [comment]
On LaunchBar (“Feedback on Action Update scheme”): if custom actions or browser hooks are the weekly snag, dual-hotkey is the low-risk compare — keep LaunchBar on ⌘Space, free Raycast on ⌥Space for a week. Only switch hard (or buy Raycast Pro) after file actions/clipboard prove they beat LaunchBar for you.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
