### ISSUE TITLE
Command-C x-callback-url now required UUID

### ISSUE THREAD

**Issue by ghost** [prenagha/launchbar#11]
I couldn't get this to work and discovered that the Command-C desktop app now requires the UUID of the iPhone/iPad, not the name. 

I adjusted the url to `var url = 'command-c://x-callback-url/copyText?deviceUUID=' + encodeURIComponent(Action.preferences.device) + '&text=' + encodeURIComponent(text);' and put my UUID in the plist file. Works great now, just wanted to let you know.

Thanks for putting this together!

**Comment by prenagha** [comment]
fixed. But I don't use command-c anymore, so didn't test. Please give it a try and if it doesn't work let me know. 
http://prenagha.github.io/launchbar/copy-iphone.html
