### ISSUE TITLE
Action Updates action fails

### ISSUE THREAD

**Issue by Pe8er** [prenagha/launchbar#12]
It throws the following error:

![](http://i.imgur.com/0l9VfQa.png)

**Comment by prenagha** [comment]
I can't recreate that here. May have something to do with an action you have or your setup. I have seen something similar when the LB actions directory is a soft-link.
I added some additional error handling and released version 2.6 of the update action. Download that and give it a try. 
http://prenagha.github.io/launchbar/updates.html
If you are still having a problem please send me the Console output from the action update action.

**Comment by prenagha** [comment]
I can't recreate this here. May have something to do with a specific action. Also have seen something like this before when the LB actions directory is a soft-link.
I have updated the update action to version 2.6 and added some error handling. Please download and give it a try
http://prenagha.github.io/launchbar/updates.html

If you are still having trouble please reopen this issue and paste in the Console log output from the action

**Comment by Pe8er** [comment]
2.6 works, thank you!
