### ISSUE TITLE
Path to SwitchAudioSource command

### ISSUE THREAD

**Issue by sealfur** [prenagha/launchbar#16]
Not sure if this is true for all, but I think it might be the default scenario on Mac OS 11:

I needed to adjust line 2 to read:
```
CMD=/opt/homebrew/bin/SwitchAudioSource
```

Default paths seem to have changed.

_(also, thanks for making this)_

**Comment by Joilence** [comment]
@sealfur According to [Installation — Homebrew Documentation](https://docs.brew.sh/Installation):

> This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon)

The path change on your side is probably due to you are using an Apple Silicon Mac (Mac with M1).

**Comment by prenagha** [comment]
Merged and bumped version number on the action. Thanks all.

**Comment by sealfur** [comment]
> @sealfur According to [Installation — Homebrew Documentation](https://docs.brew.sh/Installation):
> 
> > This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon)
> 
> The path change on your side is probably due to you are using an Apple Silicon Mac (Mac with M1).

Busy couple of weeks. Sorry, @Joilence . I am using Silicon Mac. It's causing me just some mild annoyance. Thanks for updating and merging etc.
