### ISSUE TITLE
Updates Action reports: LaunchBar: Newer version available   6.15 ➔ 6.14.1

### ISSUE THREAD

**Issue by Ptujec** [prenagha/launchbar#19]

**Comment by prenagha** [comment]
Thanks @Ptujec . Fixed now.

**Comment by Ptujec** [comment]
Thanks! I also made some new icons … because there where a couple missing. If you like I can send a pull request
<img width="646" alt="Bildschirmfoto 2022-01-17 um 22 50 00" src="https://user-images.githubusercontent.com/617932/149840712-a66a9de6-0214-413f-b1a9-1d637130ac74.png">

**Comment by prenagha** [comment]
Sure. PR would be great. Thanks.

**Comment by Ptujec** [comment]
Ok. I hope I did it right. I'm not very experienced in that.
