### ISSUE TITLE
Action Updates: Automatic downloading problematic?

### ISSUE THREAD

**Issue by hlissner** [prenagha/launchbar#2]
Automatic downloading seems imposing, and possibly problematic for actions that have **a)** no direct-download link or **b)** are part of a larger repository of actions.

Without a download link, the action doesn't know what to do. And if I use the github "download zip" link, File.readData will get hit several times for the same file, and potentially File.writeData, depending on how it handles filename collisions.

Suggestions:
- Make it a two-step process. Press enter on an action with an update to initiate the download and select the file in launchbar. Perhaps add an "Update All" child-action to force it.
- Add some simple regex/string matching to detect if LBDownload points to a file (ends in `\.(zip|tar(\.gz)?|lbaction)` or an url (in which case, open the browser maybe?)

**Comment by prenagha** [comment]
Some of that I had considered... keep in mind
- the `LBDownload` key is optional. If it is absent then that is the action telling the updater action not to try and download the new version
- the user of my update action can add a local property in the action's preferences file to turn off downloading entirely: set `DownloadDir` key in preferences to `SKIP`

If I do download the new version then the result in LB says "Newer version of xxx was downloaded" and the item has the path property set to the downloaded file so you can just hit enter to install it

If I do not download the new version then the result in LB says "Newer version of xxx is available" and the url is set on the item so if you hit enter it opens up to `LBWebsite` key

Does that address your concerns?

**Comment by prenagha** [comment]
I also made a change 1a2650f5b81ac974b852960c888a63111530736c to support the `LBDownload` pointing to any file type, including zip, no longer assuming and forcing .lbaction.
I also include the version number in the download file.
I do see your point about someone giving an entire repo as the download and it doing that multiple times... but I would argue someone doing that is incorrectly using `LBDownload` - it is defined as a URL to the file package to download the latest version _of that action_. If such a URL is not available then the action should omit the `LBDownload` key and setup `LBWebsite` per normal

**Comment by hlissner** [comment]
Oh, you're right. I missed the LBWebsite fallback. That does address my concerns, though I insist on a preference (or modifier key) for disabling auto-downloading (i.e. as if all actions were `SKIP`ed), for convenience sake. I can file the PR if you'd like.

**Comment by prenagha** [comment]
You can set `DownloadDir` in prefs to `SKIP` to turn off auto downloading entirely. I have released v1.3 d3ef885c25fde90e91ff88c3a921f4714b2577fe which gives you an LB item to enable/disable right from within the action. Also sets up default preference file so you can see the options and an edit preferences item from within the action to take you there

**Comment by youtextme** [comment]
If this LaunchBar action friction (“Action Updates: Automatic downloading problematic?” on launchbar) is eating your week: keep LaunchBar on ⌘Space and put free Raycast on ⌥Space for a dual-hotkey trial. Only make Raycast primary (or buy Pro) after extensions/clipboard/scripts beat your daily LaunchBar actions — free-first, no prepaid swap.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
