### ISSUE TITLE
Getting JSON parse error

### ISSUE THREAD

**Issue by echolock** [prenagha/launchbar#22]
Getting the error below when I try to use SwitchAudio. It was working fine until recently.

Error
SyntaxError: JSON Parse error: Unterminated string

**Comment by prenagha** [comment]
Working for me... hmmm....
Do you get that error when first executing the action or after picking an input/output to switch to?

Can you run the `audio.sh` script from the command line and paste the output back here

Should be in something like

`$HOME/Library/Application Support/LaunchBar/Actions/Switch Audio.lbaction/Contents/Scripts/audio.sh`

**Comment by prenagha** [comment]
Also let me know what `uname -m` output is?
And where `SwitchAudioSource` is located?
And anything change recently on your end?

**Comment by echolock** [comment]
When first executing it happens, don’t get to the list of outputs to choose one.

Can you give me more detail on how to get the results you need, now sure how to get this:
Also let me know what uname -m output is?
And where SwitchAudioSource is located?
And anything change recently on your end?


Output of audio.sh:

{
  "currentInput": "Core::init - HAL-Plugin
Display Audio",
  "currentOutput": "Core::init - HAL-Plugin
Display Audio",
  "inputs": [ "Core::init - HAL-Plugin", "Built-in Line Input", "Built-in Digital Input", "Display Audio", "iShowU Audio Capture", "ZoomAudioDevice" ],
  "outputs": [ "Core::init - HAL-Plugin", "Built-in Output", "Built-in Line Output", "Built-in Digital Output", "Display Audio", "iShowU Audio Capture", "ZoomAudioDevice" ]
}

**Comment by prenagha** [comment]
Run `uname -m` from command line and let me know the output

For the other, want to see where the `SwitchAudioSource` binary is installed. Is it in
`/opt/homebrew/bin/SwitchAudioSource`
or
`/usr/local/bin/SwitchAudioSource`
or other?

For the output of `audio.sh`, is that the exact output, like there is a newline between `Hal-Plugin` and `Display Audio`?
That is likely causing the JSON parsing problem

**Comment by echolock** [comment]
uname -m
x86_64

SwitchAudioSource is in:
/usr/local/bin/SwitchAudioSource

Yes, that is the exact output of audio.sh and there is a new line in the terminal.

**Comment by prenagha** [comment]
Please run these 3 commands and let me know the output for each

```
SwitchAudioSource -a -t input
SwitchAudioSource -a -t input | tr '\n' '^'
SwitchAudioSource -a -t input | tr '\r' '^'
```

**Comment by echolock** [comment]
SwitchAudioSource -a -t input
Core::init - HAL-Plugin
Built-in Line Input (input)
Built-in Digital Input (input)
Display Audio (input)
iShowU Audio Capture (input)
ZoomAudioDevice (input)

SwitchAudioSource -a -t input | tr '\n' '^'
Core::init - HAL-Plugin^Built-in Line Input (input)^Built-in Digital Input (input)^Display Audio (input)^iShowU Audio Capture (input)^ZoomAudioDevice (input)^

SwitchAudioSource -a -t input | tr '\r' '^'
Core::init - HAL-Plugin
Built-in Line Input (input)
Built-in Digital Input (input)
Display Audio (input)
iShowU Audio Capture (input)
ZoomAudioDevice (input)

**Comment by prenagha** [comment]
I can't see how the newline is getting in there, but I made some general cleanup changes and committed them 7fa64929d09aa626c77fa1f93fdc502124bf6562
Please update the action and retry
If still a problem then please run `audio.sh` from the command line, output to a file, and attach the file here
`$HOME/Library/Application Support/LaunchBar/Actions/Switch Audio.lbaction/Contents/Scripts/audio.sh > $HOME/Desktop/output.txt`

**Comment by echolock** [comment]
Still not working with the latest version. Output.txt file attached
[output.txt](https://github.com/prenagha/launchbar/files/8505616/output.txt)
.

**Comment by prenagha** [comment]
ok, made another change 6e9ca52c03af3c991389c3cc32aa37ed08b4fbf2
please update to latest version 2.7 and try again

**Comment by echolock** [comment]
Okay, thanks! The JSON error is not coming up and the audio is switching, but why is it showing this Core::init - HAL-Plugin twice? It's not an available audio source in the Sound system prefs.
![Screen Shot 2022-04-18 at 10 27 55 AM](https://user-images.githubusercontent.com/17464684/163823299-fd806d11-e386-45ea-b3f6-d3f8be927a1a.png)
.

**Comment by prenagha** [comment]
The headphone icon means it is an output, the mic icon means it is an input
So whatever that is, it is both an input and output option
The action uses the [switchaudio osx](https://github.com/deweller/switchaudio-osx) package to actually do all the audio stuff, so you'd have to ask over there why what shows up.
Glad we figured this one out finally

**Comment by youtextme** [comment]
If this LaunchBar action friction (“Getting JSON parse error” on launchbar) is eating your week: keep LaunchBar on ⌘Space and put free Raycast on ⌥Space for a dual-hotkey trial. Only make Raycast primary (or buy Pro) after extensions/clipboard/scripts beat your daily LaunchBar actions — free-first, no prepaid swap.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
