### ISSUE TITLE
Forecast Action update? 

### ISSUE THREAD

**Issue by ahaghgoo** [prenagha/launchbar#24]
Just wondering if there is an alternate way of obtaining the necessary API to get the forecast action to work properly?

**Comment by prenagha** [comment]
Apple bought Darksky, so the API this uses is no longer available. Apple does apparently have [WeatherKit](https://developer.apple.com/weatherkit/get-started/) which does have a REST API, but that requires a paid Apple developer account.

**Comment by ahaghgoo** [comment]
If I obtain a developer account, would I be able to just use the REST API and paste it in the dialog box to get it working again?  I've been looking to get a developer account for other reasons, so just wondering if I could just replace the API and get it working again? 

--
Afshin Haghgoo
***@***.***

**Comment by prenagha** [comment]
Doubtful. But I've not tried that. 

> From: Afshin Haghgoo ***@***.***>
> Date: 2023-10-24 04:27 PM -04:00
> 
> 
> 
> If I obtain a developer account, would I be able to just use the REST API and paste it in the dialog box to get it working again? I've been looking to get a developer account for other reasons, so just wondering if I could just replace the API and get it working again? 
> 
> -- 
> Afshin Haghgoo 
> ***@***.*** 
> 
> 
>
