### ISSUE TITLE
How to update "Dismiss Notifications.lbaction"

### ISSUE THREAD

**Issue by ahaghgoo** [prenagha/launchbar#26]
Hi, 

Since updating to macOS 15 (Sequoia), the Dismiss Notifications action in LaunchBar doesn't do anything.  Is there a way to update this?  Thanks for the consideration!

**Comment by Ptujec** [comment]
@ahaghgoo Maybe I can help out until Padraic gets around to fix his version. I have my own version [here](https://github.com/Ptujec/LaunchBar/tree/master/Notifications#launchbar-actions-for-managing-notifications).

**Comment by ahaghgoo** [comment]
Nice!  Thank you!! 

--
Afshin Haghgoo
***@***.***

**Comment by prenagha** [comment]
Updated the web page to point to Christian's version instead.
