### ISSUE TITLE
Action Usage Anonymous Info

### ISSUE THREAD

**Issue by prenagha** [prenagha/launchbar#4]
Also thinking about adding anonymous action usage reporting to my action update checker.
Will make it easy to disable for folks that don't want to report.

For those that let it report it would basically http post the following to a web hook that I will collect up and periodically publish:
- timestamp
- some kind of UUID for the machine (will be anonymous but consistent)
- mac OS X version info
- launchbar version info
- current locale ('en', 'de'...)
- for each custom action installed (bundleId and bundleVersion)

(remember: each user will be able to easily see that it is turned on, and easily turn it off)

Does this sound reasonable or are folks vehemently against it?

**Comment by hlissner** [comment]
My impression is that, with LaunchBar custom actions being a niche within a niche within a niche, the usage data won't produce anything meaningful. So the data would only be a novelty (and I wouldn't want it enabled myself, on principle). I'm not a commercial action developer though. I imagine they have other ways of collecting that data via their download pages anyhow.

**Comment by ghost** [comment]
I think if you reduce the overhead and just log the **download/update** count and the **version**, then nobody consider turning the feature off and it could be useful.

**Comment by prenagha** [comment]
nobody fans of this. so won't do it.
