### ISSUE TITLE
Forecast Action not finding non-US locations

### ISSUE THREAD

**Issue by chapati23** [prenagha/launchbar#9]
Hey man,
first of all thanks for sharing your actions. Already using the Things action daily ;)
Can't get the Forecast action to to find international locations, though. anything i'm missing?
1. added my api-key
2. installed and ran the location helper
3. searching with the action only returns US results

forecast.io definitely supports international locations, searching on their website gives me data for Berlin, Germany for example. But the forecast action only returns "No locations found"

any idea why?

**Comment by prenagha** [comment]
Set country in action preferences
I think the action has settings to take you to where you can set it

**Comment by chapati23** [comment]
didn't find it in the UI, but did find the Preferences.plist, thanks.

why restrict the search to one country?

**Comment by prenagha** [comment]
from the Forecast action results in LB, Locations -> Settings ...

just thought it would be easier for people to find what they were looking for. that may perhaps be a US centric view (where we travel a lot within one country)

**Comment by chapati23** [comment]
gotcha, i just deleted the ISO code and now I can search globally without having to change preferences every time. thanks for your help =)
